### ISSUE TITLE
Device token iOS

### ISSUE THREAD

**Issue by thomashrabe** [aggarwalankush/push-notification-server#3]
Are you sure in your readme about the device token for iOS?

`DEVICE_TOKEN - if you don't have device token, in case of Ionic 2, use this tutorial or this repo 👍`

AFAIK it's the public and private key that I needed to setup on my server...

**Comment by aggarwalankush** [comment]
Yes, the instructions in readme are tested on both android and iOS device.

**Comment by thomashrabe** [comment]
Sure, but I wanted to pint out that the documentation for iOS is wrong.
Specifically it’s called public and private key files for iOS. Your documentation for iOs is a copy & paste from your Android documentation.
Just wanted to point this out so that other users do not get confused… 

Cheers,
Thomas
